name: Copy ligth module into production (test)
on:
  push:
    branches:
      - production
jobs:
  copy_to_target:
    name: Copy ligth module
    runs-on: ubuntu-latest
    steps:
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        target: "/vgz/test"
        source: "*"
